Quality check escaped ampersand
deybis17/jabref pull request #1
Opened 2023-04-08 17:52 UTC by Zylence

```[tasklist]
### Compulsory checks
- [ ] Change in `CHANGELOG.md` described in a way that is understandable for the average user (if applicable)
- [X] Tests created for changes (if applicable)
- [X] Manually tested changed features in running JabRef (always required)
- [ ] Screenshots added in PR description (for UI changes)
- [] [Checked developer's documentation](https://devdocs.jabref.org/): Is the information available and up to date? If not, I outlined it in this pull request.
- [ ] [Checked documentation](https://docs.jabref.org/): Is the information available and up to date? If not, I created an issue at <https://github.com/JabRef/user-documentation/issues> or, even better, I submitted a pull request to the documentation repository.
```

2023-04-08 18:14 UTC, KonstantinEger requested changes

2023-04-08 18:14 UTC, KonstantinEger commented on src/main/java/org/jabref/logic/integrity/AmpersandChecker.java
> +                results.add(new IntegrityMessage(Localization.lang("Found " + unescapedAmpersands + " unescaped '&'"), entry, field.getKey()));
Ich glaube das geht so nicht. Die Localization-Klasse lädt statisch die Übersetztung aus einem Resource-Bundle. D.h. da dürfen keine dynamischen Infos mit drin sein. Das betrifft auch die Tests

2023-04-08 18:21 UTC, KonstantinEger commented on src/main/java/org/jabref/logic/integrity/AmpersandChecker.java
> +                results.add(new IntegrityMessage(Localization.lang("Found " + unescapedAmpersands + " unescaped '&'"), entry, field.getKey()));
Man kann aber Parameter übergeben. Siehe:

```suggestion
                results.add(new IntegrityMessage(Localization.lang("Found %0 unescaped '&'", unescapedAmoersands), entry, field.getKey()));
```

Hab ich nicht getestet, aber im Code an anderen Stellen so gesehen

2023-04-08 19:07 UTC, Zylence commented on src/main/java/org/jabref/logic/integrity/AmpersandChecker.java
> +                results.add(new IntegrityMessage(Localization.lang("Found " + unescapedAmpersands + " unescaped '&'"), entry, field.getKey()));
Danke dir für die Info! Schaue ich mir gleich morgen genauer an.

2023-04-12 11:15 UTC, Zylence commented on src/main/java/org/jabref/logic/integrity/AmpersandChecker.java
> +                results.add(new IntegrityMessage(Localization.lang("Found " + unescapedAmpersands + " unescaped '&'"), entry, field.getKey()));
Die angefragten Änderungen wurden [angewendet](https://github.com/deybis17/jabref/pull/1/commits/5b110c2b3a6cd74ead7aec0604adec8db03b5b2c).

2023-04-15 20:24 UTC, closed without merging